[tool.poetry]
name = "goit-web-hw-02-1"
version = "0.1.0"
description = ""
authors = ["InvisUA"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
